Preprocessing code change to include all the files
Deep-Learning-CS/CourseProjectDeepLearning pull request #9
Opened 2024-11-20 18:17 UTC by ayushdh96

Hello guys, here is the code for pre processing all the files rather than one for creating the spectrogram. As discussed I'll try to add more noises to it like traffic noise, cafe noise etc. And will try to push that mid next week or end of next week.
People working with the training can use this code meanwhile.
I would like to extend my thanks to Drashti for this who helped me with the idea for the preprocessing of all the files.
Kindly let me know incase of any concern or issues.
Thanks

2024-11-20 19:47 UTC, lukebushur commented
Could you also download a python file (.py extension) version of the notebook and include it in the pull request?

2024-11-20 19:56 UTC, lukebushur requested changes
See my comment about adding a .py version of the code.

2024-11-20 22:30 UTC, sanidhaya approved these changes
Looks fine

2024-11-21 12:21 UTC, ayushdh96 commented
Sure Luke, thank you for your input. I've added the .py file as well in the pull request. Kindly let me know in case of any concern.

2024-11-21 20:23 UTC, lukebushur approved these changes
Looks good! One comment about function names--up to you whether you want to implement it.

2024-11-21 20:23 UTC, lukebushur commented on mainfile/Preprocessing.py
> +def save_mel_spectrogram(audio_path, save_path, noise_factor=0.005):
Might be helpful to separate the name of this function from the previous function. It could get confusing when trying to call a certain function when you meant to call the other one.

2024-11-22 14:40 UTC, DRASHHTIPATEL approved these changes
Sounds good! I look forward to testing these updates next week.

2024-11-24 23:02 UTC, s1ashd0t commented on mainfile/Preprocessing.py
> +
These files/dirs don't exist in the repo. Is the dataset too big to be included in the repo? Could you add a link perhaps?

2024-11-25 01:45 UTC, s1ashd0t commented
> Hello guys, here is the code for pre processing all the files rather than one for creating the spectrogram. As discussed I'll try to add more noises to it like traffic noise, cafe noise etc. And will try to push that mid next week or end of next week. People working with the training can use this code meanwhile. I would like to extend my thanks to Drashti for this who helped me with the idea for the preprocessing of all the files. Kindly let me know incase of any concern or issues. Thanks

Hey Ayush,

Here is the dataset I mentioned in class: [https://media.xiph.org/rnnoise/rnnoise_contributions.tar.gz](url)

2024-11-25 12:16 UTC, ayushdh96 commented
Thank you for 

> code looks good. One small thing same variables are defined multiple times like dataset_path etc

Yup, in the new file I'll keep that in mind when creating that.

2024-11-25 12:16 UTC, ayushdh96 commented
> > Hello guys, here is the code for pre processing all the files rather than one for creating the spectrogram. As discussed I'll try to add more noises to it like traffic noise, cafe noise etc. And will try to push that mid next week or end of next week. People working with the training can use this code meanwhile. I would like to extend my thanks to Drashti for this who helped me with the idea for the preprocessing of all the files. Kindly let me know incase of any concern or issues. Thanks
> 
> Hey Ayush,
> 
> Here is the dataset I mentioned in class: [https://media.xiph.org/rnnoise/rnnoise_contributions.tar.gz](url)

Thank you for this. I'll incorporate this in the next changes.

2024-11-25 12:17 UTC, merged